#!/usr/bin/env bash

# Copyright (C) 2019 Saalim Quadri <danascape@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

# Set Variables
# Scripts Path
SCRIPTS_PATH="$HOME/scripts"

git_alias() {
	git config --global alias.a 'add'
	git config --global alias.c 'commit'
	git config --global alias.cp 'cherry-pick'
	git config --global alias.f 'fetch'
	git config --global alias.s 'status'
}

# Call telegram config
. "$SCRIPTS_PATH"/telegram.config --source-only

# Set tg var.
sendTG() {
	curl -s "https://api.telegram.org/bot${API_KEY}/sendmessage" --data "text=${*}&chat_id=$CHAT_ID&parse_mode=HTML" >/dev/null
}

pushTG() {
	curl -F chat_id="$CHAT_ID" -F document=@"${*}" "https://api.telegram.org/bot${API_KEY}/sendDocument"
}

rq() {
	. "$SCRIPTS_PATH"/qemu/start-qemu.sh "$@"
}
