#!/usr/bin/env bash

# Copyright (C) 2019 Saalim Quadri <danascape@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

git_alias() {
	git config --global alias.a 'add'
	git config --global alias.c 'commit'
	git config --global alias.cp 'cherry-pick'
	git config --global alias.f 'fetch'
	git config --global alias.s 'status'
}
